Repository Team-MuMuk/FE, pull requests merged in 2025-08, with the labels that each got.

#96 [Feature/#95] 레시피 찜하기 API
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/api/UserRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/model/Recipe.kt
  app/src/main/java/com/example/mumuk/data/model/RecipeRank.kt
  app/src/main/java/com/example/mumuk/data/model/recipe/ClickLikeRequest.kt
  app/src/main/java/com/example/mumuk/data/model/recipe/ClickLikeResponse.kt
  app/src/main/java/com/example/mumuk/data/model/search/RecentRecipe.kt
  app/src/main/java/com/example/mumuk/data/repository/BookmarkRecipeRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/HealthAiRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/HomeRecipeRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/IngredientAiRecipeRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/RecommendRecipeRepository.kt
  app/src/main/java/com/example/mumuk/ui/bookmark/BookmarkRecipeAdapter.kt
  app/src/main/java/com/example/mumuk/ui/bookmark/BookmarkRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/CategoryRecipeCardAdapter.kt
  app/src/main/java/com/example/mumuk/ui/category/health/CategoryLowSugarFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/random/CategoryRandomRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/weight/CategoryWeightLossFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeRecipeAdapter.kt
  app/src/main/java/com/example/mumuk/ui/home/RecipeRankAdapter.kt
  app/src/main/java/com/example/mumuk/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/mumuk/ui/mypage/RecentRecipe.kt
  app/src/main/java/com/example/mumuk/ui/mypage/RecentRecipeAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeViewModel.kt
  app/src/main/java/com/example/mumuk/ui/recommend/HealthAiAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recommend/HealthRecommendFragment.kt
  app/src/main/java/com/example/mumuk/ui/recommend/IngredientAiRecipeAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recommend/IngredientRecommendFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchRecentRecipeAdapter.kt
  app/src/main/java/com/example/mumuk/ui/search/result/SearchResultAdapter.kt
  app/src/main/java/com/example/mumuk/ui/search/result/SearchResultFragment.kt
Labels: ✨ FEATURE

#99 [Refactor/#98] 찜한 레시피 UI 수정
  app/src/main/java/com/example/mumuk/data/model/Blog.kt
  app/src/main/java/com/example/mumuk/data/model/RecipeIngredient.kt
  app/src/main/java/com/example/mumuk/data/repository/BlogRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/BookmarkRecipeRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/NutritionInfoRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/RecipeIngredientRepository.kt
  app/src/main/java/com/example/mumuk/ui/bookmark/BookmarkRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/bookmark/BookmarkRecipeViewModel.kt
  app/src/main/java/com/example/mumuk/ui/recipe/BlogAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recipe/IngredientAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recipe/NutritionInfoAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeViewModel.kt
  app/src/main/java/com/example/mumuk/ui/signup/SignupStep6Fragment.kt
  app/src/main/res/drawable/ic_round.xml
  app/src/main/res/layout/fragment_bookmark_recipe.xml
  app/src/main/res/layout/fragment_recipe.xml
  app/src/main/res/layout/item_blog.xml
  app/src/main/res/layout/item_ingredient_available.xml
  app/src/main/res/layout/item_ingredient_missing.xml
  app/src/main/res/layout/item_shop.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: ✨ FEATURE, ♻️ REFACTOR, 🎨 DESIGN

#102 [Feature/#101] 레시피 상세 조회 API
  .kotlin/errors/errors-1754211989030.log
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/api/UserRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/model/RecipeIngredient.kt
  app/src/main/java/com/example/mumuk/data/model/search/UserRecipeDetailData.kt
  app/src/main/java/com/example/mumuk/data/model/search/UserRecipeDetailResponse.kt
  app/src/main/java/com/example/mumuk/data/repository/UserRecipeRepository.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeViewModel.kt
  app/src/main/res/layout/fragment_search_result.xml
Labels: ✨ FEATURE

#107 [Feature/#105] 랜덤 레시피 추천 API
  app/src/main/java/com/example/mumuk/data/api/RandomRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/model/Recipe.kt
  app/src/main/java/com/example/mumuk/data/model/category/RandomRecipe.kt
  app/src/main/java/com/example/mumuk/data/model/category/RandomRecipeResponse.kt
  app/src/main/java/com/example/mumuk/ui/category/CategoryRecipeCardAdapter.kt
  app/src/main/java/com/example/mumuk/ui/category/random/CategoryRandomRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeRecipeAdapter.kt
  app/src/main/res/layout/item_recipe.xml
Labels: ✨ FEATURE

#111 [Feature/#108] 카테고리 레시피 API
  app/src/main/java/com/example/mumuk/data/api/CategoryRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/model/category/CategoryRecipe.kt
  app/src/main/java/com/example/mumuk/data/model/category/CategoryRecipeResponse.kt
  app/src/main/java/com/example/mumuk/ui/category/health/CategoryLowSugarFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/weight/CategoryWeightLossFragment.kt
Labels: ✨ FEATURE

#114 [Feature/#103] 개인정보 동의 화면 추가
  app/src/main/java/com/example/mumuk/ui/signup/SignupCompleteFragment.kt
  app/src/main/java/com/example/mumuk/ui/signup/SignupStep6Fragment.kt
  app/src/main/java/com/example/mumuk/ui/signup/TermsPrivacyFragment.kt
  app/src/main/res/drawable/btn_confirm_border.xml
  app/src/main/res/drawable/gray_border_background.xml
  app/src/main/res/drawable/ic_check_blue.png
  app/src/main/res/drawable/ic_check_gray.png
  app/src/main/res/drawable/ic_checkbox.xml
  app/src/main/res/layout/fragment_terms_privacy.xml
  app/src/main/res/values/strings.xml
Labels: ✨ FEATURE, 🎨 DESIGN

#126 [Refactor#125] 소셜 로그인 API 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mumuk/IntroActivity.kt
  app/src/main/java/com/example/mumuk/data/api/AuthApiService.kt
  app/src/main/java/com/example/mumuk/data/api/AuthTokenInterceptor.kt
  app/src/main/java/com/example/mumuk/data/model/auth/KakaoLoginResponse.kt
  app/src/main/java/com/example/mumuk/data/model/auth/NaverLoginResponse.kt
  app/src/main/java/com/example/mumuk/ui/login/LoginIntroActivity.kt
  app/src/main/java/com/example/mumuk/ui/mypage/MyPageFragment.kt
  app/src/main/res/xml/network_security_config.xml
Labels: ✨ FEATURE, ♻️ REFACTOR

#127 [Fix/#119] 최근 검색어 API 오류
  .kotlin/errors/errors-1754571881637.log
  app/src/main/res/layout/fragment_search_result.xml
Labels: 🐛 FIX, ✨ FEATURE

#129 [Refactor/#128] 검색 UI 수정
  .kotlin/errors/errors-1754760232213.log
  app/src/main/java/com/example/mumuk/data/model/search/RecentRecipe.kt
  app/src/main/java/com/example/mumuk/ui/search/autocomplete/SearchAutocompleteAdapter.kt
  app/src/main/java/com/example/mumuk/ui/search/autocomplete/SearchAutocompleteFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/autocomplete/SearchAutocompleteKeyword.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchRecentRecipeAdapter.kt
  app/src/main/res/layout/item_search_autocomplete.xml
Labels: ✨ FEATURE, ♻️ REFACTOR

#131 [Feature#116] 레시피 상세 API 연결
  app/build.gradle.kts
  app/src/main/java/com/example/mumuk/data/api/UserRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/model/recipe/BlogResponse.kt
  app/src/main/java/com/example/mumuk/data/model/recipe/SearchedBlog.kt
  app/src/main/java/com/example/mumuk/data/repository/OgImageRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/UserRecipeRepository.kt
  app/src/main/java/com/example/mumuk/ui/bookmark/BookmarkRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/health/CategoryLowSugarFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/random/CategoryRandomRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/weight/CategoryWeightLossFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
  app/src/main/java/com/example/mumuk/ui/recipe/BlogAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recipe/IngredientAdapter.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeViewModel.kt
  app/src/main/java/com/example/mumuk/ui/recommend/HealthRecommendFragment.kt
  app/src/main/java/com/example/mumuk/ui/recommend/IngredientRecommendFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/result/SearchResultFragment.kt
  app/src/main/res/layout/fragment_recipe.xml
  app/src/main/res/layout/item_blog.xml
  app/src/main/res/layout/item_recipe.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ FEATURE, 🎨 DESIGN

#134 [Refactor/#132] 인기 검색어 API 수정
  app/src/main/java/com/example/mumuk/data/api/RandomRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RecipeSearchApiService.kt
  app/src/main/java/com/example/mumuk/data/model/search/RecipeSearchItem.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/result/SearchResultFragment.kt
Labels: ✨ FEATURE, ♻️ REFACTOR

#141 [Refactor/#138] 카테고리 API 수정
  .kotlin/errors/errors-1754900855977.log
  app/src/main/java/com/example/mumuk/data/api/CategoryRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/model/category/CategoryRecipe.kt
  app/src/main/java/com/example/mumuk/ui/category/CategoryRecipeCardAdapter.kt
  app/src/main/java/com/example/mumuk/ui/category/health/CategoryLowSugarFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/weight/CategoryWeightLossFragment.kt
Labels: ✨ FEATURE, ♻️ REFACTOR

#143 [Refactor/#142] 랜덤 레시피 API 수정
  app/src/main/java/com/example/mumuk/data/model/category/RandomRecipe.kt
  app/src/main/java/com/example/mumuk/ui/category/random/CategoryRandomRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
Labels: ✨ FEATURE, ♻️ REFACTOR

#147 [Refactor/#145] 마이페이지 ui 수정
  app/src/main/java/com/example/mumuk/ui/login/FindAccountFragment.kt
  app/src/main/java/com/example/mumuk/ui/mypage/ProfileFragment.kt
  app/src/main/java/com/example/mumuk/ui/signup/TermsPrivacyFragment.kt
  app/src/main/res/drawable/ic_arrow_white.png
  app/src/main/res/layout/fragment_signup_complete.xml
Labels: ♻️ REFACTOR, 🎨 DESIGN

#160 [Feature#159] 상세 레시피 API 추가 연
  app/src/main/java/com/example/mumuk/data/api/NaverShoppingApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/model/recipe/NaverShoppingItem.kt
  app/src/main/java/com/example/mumuk/data/repository/ShopRepository.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/recipe/RecipeViewModel.kt
  app/src/main/java/com/example/mumuk/ui/recipe/ShopAdapter.kt
  app/src/main/res/layout/fragment_recipe.xml
  app/src/main/res/layout/item_ingredient_available.xml
  app/src/main/res/layout/item_ingredient_missing.xml
  app/src/main/res/layout/item_shop.xml
Labels: ✨ FEATURE, ♻️ REFACTOR, 🎨 DESIGN

#171 Feature: 푸시 알림 조회 API
  app/src/main/java/com/example/mumuk/data/api/AlarmApiService.kt
  app/src/main/java/com/example/mumuk/data/api/CategoryRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RandomRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/model/alarm/AlarmItem.kt
  app/src/main/java/com/example/mumuk/data/model/alarm/AlarmResponse.kt
  app/src/main/java/com/example/mumuk/ui/alarm/AlarmAdapter.kt
  app/src/main/java/com/example/mumuk/ui/alarm/AlarmFragment.kt
  app/src/main/java/com/example/mumuk/ui/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_alarm.png
  app/src/main/res/drawable/ic_alarm_new.png
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_home.xml
Labels: ✨ FEATURE

#200 [Refactor#192] 건강정보 토글 로직 변경
  app/src/main/java/com/example/mumuk/ui/health/HealthCompleteFragment.kt
  app/src/main/java/com/example/mumuk/ui/health/HealthEditFragment.kt
  app/src/main/java/com/example/mumuk/ui/health/HealthStep1Fragment.kt
  app/src/main/java/com/example/mumuk/ui/health/HealthStep2Fragment.kt
  app/src/main/java/com/example/mumuk/ui/health/HealthViewModel.kt
  app/src/main/res/layout/fragment_signup_step1.xml
  app/src/main/res/layout/fragment_signup_step2.xml
  app/src/main/res/layout/fragment_signup_step3.xml
  app/src/main/res/layout/fragment_signup_step4.xml
  app/src/main/res/layout/fragment_signup_step5.xml
  app/src/main/res/layout/fragment_signup_step6.xml
Labels: ✨ FEATURE, ♻️ REFACTOR

#216 [Refactor/#215] 인기 검색어 UI 수정
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: ♻️ REFACTOR, 🎨 DESIGN
