Repository Team-MuMuk/FE, pull requests merged in 2025-07, with the labels that each got.

#52 [Fix#45] category, search ui 수정
  app/src/main/java/com/example/mumuk/ui/category/health/CategoryLowSugarFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/random/CategoryRandomRecipeFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/weight/CategoryWeightLossFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/result/SearchResultFragment.kt
  app/src/main/res/layout/category_custom_tab.xml
  app/src/main/res/layout/fragment_category_low_sugar.xml
  app/src/main/res/layout/fragment_category_random_recipe.xml
  app/src/main/res/layout/fragment_category_recipe_list.xml
  app/src/main/res/layout/fragment_category_weight_loss.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/item_recent_recipe.xml
  app/src/main/res/layout/item_recipe.xml
Labels: 🐛 FIX

#60 [Refactor/#53] 홈 화면 등 디자인 변경
  app/src/main/java/com/example/mumuk/data/model/RecipeRank.kt
  app/src/main/java/com/example/mumuk/data/repository/HomeRecipeRepository.kt
  app/src/main/java/com/example/mumuk/data/repository/RecipeRankRepository.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/RecipeRankAdapter.kt
  app/src/main/res/color/bottom_nav_item_color.xml
  app/src/main/res/drawable/btn_add.xml
  app/src/main/res/drawable/btn_bookmarked.xml
  app/src/main/res/drawable/btn_date.xml
  app/src/main/res/drawable/btn_health.xml
  app/src/main/res/drawable/btn_ingredient.xml
  app/src/main/res/drawable/btn_liked.xml
  app/src/main/res/drawable/btn_personal.xml
  app/src/main/res/drawable/btn_search.xml
  app/src/main/res/drawable/btn_today.xml
  app/src/main/res/font/custom_font_family.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_rank.xml
  app/src/main/res/layout/item_recipe.xml
  app/src/main/res/values/themes.xml
Labels: ♻️ REFACTOR, 🎨 DESIGN

#65 [Refactor/#64] 재료 등록 화면 수정
  app/build.gradle.kts
  app/src/main/java/com/example/mumuk/data/repository/IngredientRepository.kt
  app/src/main/java/com/example/mumuk/ui/ingredient/AddIngredientFragment.kt
  app/src/main/java/com/example/mumuk/ui/ingredient/ExpiringIngredientAdapter.kt
  app/src/main/java/com/example/mumuk/ui/ingredient/IngredientListFragment.kt
  app/src/main/res/font/custom_font_family.xml
  app/src/main/res/layout/dialog_ingredient_added.xml
  app/src/main/res/layout/fragment_add_ingredient.xml
  app/src/main/res/layout/item_ingredient.xml
  app/src/main/res/layout/item_ingredient_expiring.xml
  app/src/main/res/values/colors.xml
  gradle.properties
  settings.gradle.kts
Labels: ♻️ REFACTOR, 🎨 DESIGN

#68 [Feature/#67] 추천 검색어 API
  .kotlin/errors/errors-1753685467358.log
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/api/SuggestKeywordApiService.kt
  app/src/main/java/com/example/mumuk/data/model/search/SuggestKeywordResponse.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchFragment.kt
Labels: ✨ FEATURE

#75 [Feature/#72] 최근 본 레시피 API
  app/build.gradle.kts
  app/src/main/java/com/example/mumuk/data/api/RecentRecipeApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/model/search/RecentRecipe.kt
  app/src/main/java/com/example/mumuk/data/model/search/RecentRecipeData.kt
  app/src/main/java/com/example/mumuk/data/model/search/RecentRecipeResponse.kt
  app/src/main/java/com/example/mumuk/ui/search/SearchRecentRecipeViewModel.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchFragment.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchRecentRecipeAdapter.kt
  gradlew
Labels: ✨ FEATURE

#81 [Refactor/#80] 홈 화면 UI 변경
  app/src/main/java/com/example/mumuk/data/repository/HomeRecipeRepository.kt
  app/src/main/java/com/example/mumuk/ui/health/HealthEditFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
  app/src/main/res/drawable/ic_logo_home.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_rank.xml
Labels: ♻️ REFACTOR, 🎨 DESIGN

#82 [Feature/#78] 비밀번호 변경 API 연결
  app/src/main/java/com/example/mumuk/data/api/AuthApiService.kt
  app/src/main/java/com/example/mumuk/data/model/auth/CheckCurrentPwRequest.kt
  app/src/main/java/com/example/mumuk/data/model/auth/ReissuePwRequest.kt
  app/src/main/java/com/example/mumuk/data/model/auth/ReissuePwResponse.kt
  app/src/main/java/com/example/mumuk/ui/login/ChangePwFragment.kt
  app/src/main/java/com/example/mumuk/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/example/mumuk/ui/mypage/SubChangePw1Fragment.kt
  app/src/main/java/com/example/mumuk/ui/mypage/SubChangePw2Fragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: ✨ FEATURE

#86 [Fix/#85] refreshToken 자동 로그인처리
  app/src/main/java/com/example/mumuk/IntroActivity.kt
  app/src/main/java/com/example/mumuk/data/api/AuthApiService.kt
Labels: 🐛 FIX

#88 [Refactor/#87] 알러지 정보 수정 API 변경
  app/src/main/java/com/example/mumuk/data/api/AllergyApiService.kt
  app/src/main/java/com/example/mumuk/data/model/allergy/AllergyOption.kt
  app/src/main/java/com/example/mumuk/data/model/allergy/AllergyOptionsResponse.kt
  app/src/main/java/com/example/mumuk/data/model/allergy/ToggleAllergyRequest.kt
  app/src/main/java/com/example/mumuk/data/model/allergy/ToggleAllergyResponse.kt
  app/src/main/java/com/example/mumuk/ui/health/HealthEditFragment.kt
  app/src/main/java/com/example/mumuk/ui/health/HealthManagementFragment.kt
  app/src/main/java/com/example/mumuk/ui/home/HomeFragment.kt
Labels: 🐛 FIX, ♻️ REFACTOR

#91 [Feature/#83] 재료 등록 화면 API 연결
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mumuk/MyFirebaseMessagingService.kt
  app/src/main/java/com/example/mumuk/data/api/IngredientApiService.kt
  app/src/main/java/com/example/mumuk/data/api/RetrofitClient.kt
  app/src/main/java/com/example/mumuk/data/model/ingredient/IngredientRegisterRequest.kt
  app/src/main/java/com/example/mumuk/data/model/ingredient/IngredientRegisterResponse.kt
  app/src/main/java/com/example/mumuk/data/model/ingredient/IngredientResponse.kt
  app/src/main/java/com/example/mumuk/data/repository/IngredientRepository.kt
  app/src/main/java/com/example/mumuk/ui/ingredient/AddIngredientFragment.kt
  app/src/main/java/com/example/mumuk/ui/ingredient/IngredientAdapter.kt
  app/src/main/java/com/example/mumuk/ui/ingredient/IngredientListFragment.kt
  app/src/main/java/com/example/mumuk/ui/recommend/IngredientRecommendFragment.kt
  build.gradle.kts
Labels: ✨ FEATURE

#92 [Refactor/#77] Search & Category UI 수정
  .kotlin/errors/errors-1753842462430.log
  app/build.gradle.kts
  app/src/main/java/com/example/mumuk/ui/category/CategoryItem.kt
  app/src/main/java/com/example/mumuk/ui/category/CategoryItemAdapter.kt
  app/src/main/java/com/example/mumuk/ui/category/health/CategoryHealthFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/random/CategoryRandomFragment.kt
  app/src/main/java/com/example/mumuk/ui/category/weight/CategoryWeightFragment.kt
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_category_health.xml
  app/src/main/res/layout/fragment_category_low_sugar.xml
  app/src/main/res/layout/fragment_category_random.xml
  app/src/main/res/layout/fragment_category_random_recipe.xml
  app/src/main/res/layout/fragment_category_weight.xml
  app/src/main/res/layout/fragment_category_weight_loss.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_autocomplete.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_recent_recipe.xml
  app/src/main/res/layout/item_search_autocomplete.xml
  app/src/main/res/layout/item_search_popular_keyword.xml
  app/src/main/res/layout/item_search_recent_keyword_chip.xml
  app/src/main/res/layout/item_search_suggest_keyword_chip.xml
  app/src/main/res/values/colors.xml
Labels: ♻️ REFACTOR, 🎨 DESIGN

#94 [Fix#93] 최근 검색어 삭제 API 오류 수정
  app/src/main/java/com/example/mumuk/data/model/search/RecentSearchResponse.kt
  app/src/main/java/com/example/mumuk/ui/search/main/SearchFragment.kt
Labels: 🐛 FIX, ✨ FEATURE
